### ISSUE TITLE
incorrect string concatenation in lang file

### ISSUE THREAD

**Issue by danmarsden** [DSI-Universite-Rennes2/moodle-local_debugtoolbar#1]
string concatentaion in the lang packs is not allowed - it causes problems for the Moodle translation tool

eg:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

each string must be contained within one set of quotes eg:
$string['test'] = "sometext somemoretext";

**Comment by jboulen** [comment]
Fixed. Thanks !
