### ISSUE TITLE
styles.css not specific enough

### ISSUE THREAD

**Issue by danmarsden** [DSI-Universite-Rennes2/moodle-local_debugtoolbar#2]
https://github.com/DSI-Universite-Rennes2/moodle-local_debugtoolbar/blob/master/styles.css#L1

That line isn't really specific enough to your plugin - I'd assume that your debugtoolbar doesn't display for "all users" but that css will definitely apply for all users even when the plugin is "disabled" so you should make it more specific

standard template response below, but it might have some useful info...

---
in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simlar names are used. 

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by jboulen** [comment]
Fixed. Thanks !
