### ISSUE TITLE
lib.php should only contain functions - not in-line php code

### ISSUE THREAD

**Issue by danmarsden** [DSI-Universite-Rennes2/moodle-local_debugtoolbar#3]
the lines at the top of this file:
https://github.com/DSI-Universite-Rennes2/moodle-local_debugtoolbar/blob/master/lib.php#L27

shouldn't be set in lib.php but in a hook or a function call somewhere instead.

**Comment by danmarsden** [comment]
I'd probably move that error handling code into a callback - eg something like the after_login or similar:

https://docs.moodle.org/dev/Callbacks

**Comment by jboulen** [comment]
Thank you Dan ! I didn't know this documentation page. It could be useful for other thing.
